bahmnilab_url: "https://s3.ap-south-1.amazonaws.com/possible-artifacts/openelis.war"
bahmni_lab_temp_files:
  - bahmni-lab.war
  - possible-bahmni-lab
possible_lab:
  - config.rb
  - css
  - documentation
  - fonts
  - images
  - index.jsp
  - LICENSE
  - media
  - META-INF
  - pages
  - scripts
  - tree_images
  - WEB-INF